Fix Bundler crashing when installing very old gems:
- ### Problem

  There is a regression where bundler can longer install gems that
  were packaged a long time ago, like the [memoize gem](https://rubygems.org/gems/memoize).

  Bundler will crash with such error:

  ```
  Installing memoize 1.3.1
  --- ERROR REPORT TEMPLATE -------------------------------------------------------

  NoMethodError: undefined method 'as_list' for nil
  /Users/edouard/src/opensource/rubygems/lib/rubygems/dependency.rb:146:in 'Gem::Dependency#requirements_list'
  ```

  ### Context

  These very old gems were packaged at the time were a
  `Gem::Dependency` had no ivars `requirement`.
  This is what the dumped gemspec looks like:

  ```
  dependencies:
  - !ruby/object:Gem::Dependency
  name: test-unit
  type: :development
  version_requirement:
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: 2.0.2
    version:
  ```

  As opposed to a gem that was packaged more recently:

  ```
  - !ruby/object:Gem::Dependency
  name: minitest-global_expectations
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '0'
  ```

  The change we made in https://github.com/ruby/rubygems/commit/cbe57bbbd71e8ac7fed686ae7d13a2fd1bd2e5b2#diff-5ccc8aa468df013cc970580e88642417da12284da6529a4885b9abf447ae95edL529
  broke old gem installation.

  ### Solution

  If `requirement` isn't set in the hash, look for
  `version_requirements` instead.